// Generated by Claude - reviewed by Jose Ramirez - 2026-04-08

// Base de datos mock de libros para simular resultados de busqueda
const mockBooks = [
  {
    id: 1,
    title: 'Don Quijote de la Mancha',
    author: 'Miguel de Cervantes',
    year: 1605,
    genre: 'Novela'
  },
  {
    id: 2,
    title: 'Cien Anos de Soledad',
    author: 'Gabriel Garcia Marquez',
    year: 1967,
    genre: 'Realismo magico'
  },
  {
    id: 3,
    title: 'El Principito',
    author: 'Antoine de Saint-Exupery',
    year: 1943,
    genre: 'Fabula'
  },
  {
    id: 4,
    title: 'Harry Potter y la Piedra Filosofal',
    author: 'J.K. Rowling',
    year: 1997,
    genre: 'Fantasia'
  },
  {
    id: 5,
    title: '1984',
    author: 'George Orwell',
    year: 1949,
    genre: 'Distopia'
  },
  {
    id: 6,
    title: 'El Senor de los Anillos',
    author: 'J.R.R. Tolkien',
    year: 1954,
    genre: 'Fantasia'
  }
];

/**
 * Handler para GET /books/:title
 * Busca libros cuyo titulo contenga el texto proporcionado (case-insensitive).
 * Devuelve un JSON con formato { success, data, error }.
 */
function searchBooks(req, res) {
  try {
    // Extrae el parametro :title de la URL
    const { title } = req.params;

    // Validacion: comprueba que el parametro no este vacio
    if (!title || title.trim() === '') {
      return res.status(400).json({
        success: false,
        data: null,
        error: 'El parametro "title" es obligatorio y no puede estar vacio'
      });
    }

    // Busca libros cuyo titulo contenga el texto (sin distinguir mayusculas/minusculas)
    const searchTerm = title.toLowerCase().trim();
    const results = mockBooks.filter(book =>
      book.title.toLowerCase().includes(searchTerm)
    );

    // Si no se encontraron resultados, responde con 404
    if (results.length === 0) {
      return res.status(404).json({
        success: false,
        data: null,
        error: `No se encontraron libros con el titulo "${title}"`
      });
    }

    // Devuelve los libros encontrados
    return res.status(200).json({
      success: true,
      data: results,
      error: null
    });

  } catch (error) {
    // Captura cualquier error inesperado y responde con 500
    return res.status(500).json({
      success: false,
      data: null,
      error: 'Error interno del servidor'
    });
  }
}

// Exporta el handler y los datos mock (mock se exporta para los tests)
module.exports = { searchBooks, mockBooks };
