// Generated by Claude - reviewed by Jose Ramirez - 2026-04-08

const express = require('express');
const { searchBooks } = require('./api/handler');

// Crea la aplicacion Express
const app = express();

// Puerto del servidor (usa variable de entorno o 3000 por defecto)
const PORT = process.env.PORT || 3000;

// Ruta principal: GET /books/:title - busca libros por titulo
app.get('/books/:title', searchBooks);

// Inicia el servidor solo si se ejecuta directamente (no en tests)
if (require.main === module) {
  app.listen(PORT, () => {
    console.log(`Servidor corriendo en http://localhost:${PORT}`);
  });
}

// Exporta app para poder usarla en tests
module.exports = app;
