// Generated by Claude - reviewed by Jose Ramirez - 2026-04-08

const chai = require('chai');
const expect = chai.expect;

// Mock de los objetos req y res de Express para poder testear el handler sin levantar servidor
const { searchBooks } = require('../../src/api/handler');

/**
 * Crea un objeto res falso que simula el comportamiento de Express.
 * Captura el status code y el JSON de respuesta para poder hacer asserts.
 */
function createMockRes() {
  const res = {
    statusCode: null,
    body: null,
    status(code) {
      res.statusCode = code;
      return res; // Permite encadenar .status(200).json(...)
    },
    json(data) {
      res.body = data;
      return res;
    }
  };
  return res;
}

describe('GET /books/:title', () => {

  // HAPPY PATH - Busqueda que devuelve resultados
  it('deberia devolver libros cuando el titulo coincide', () => {
    const req = { params: { title: 'quijote' } };
    const res = createMockRes();

    searchBooks(req, res);

    expect(res.statusCode).to.equal(200);
    expect(res.body.success).to.equal(true);
    expect(res.body.data).to.be.an('array');
    expect(res.body.data.length).to.be.greaterThan(0);
    expect(res.body.data[0].title).to.include('Quijote');
  });

  // HAPPY PATH - Busqueda case-insensitive
  it('deberia buscar sin distinguir mayusculas/minusculas', () => {
    const req = { params: { title: 'PRINCIPITO' } };
    const res = createMockRes();

    searchBooks(req, res);

    expect(res.statusCode).to.equal(200);
    expect(res.body.success).to.equal(true);
    expect(res.body.data.length).to.equal(1);
    expect(res.body.data[0].author).to.equal('Antoine de Saint-Exupery');
  });

  // ERROR - Titulo no encontrado
  it('deberia devolver 404 si no encuentra libros', () => {
    const req = { params: { title: 'libroquenoexiste' } };
    const res = createMockRes();

    searchBooks(req, res);

    expect(res.statusCode).to.equal(404);
    expect(res.body.success).to.equal(false);
    expect(res.body.error).to.be.a('string');
    expect(res.body.data).to.be.null;
  });

  // ERROR - Titulo vacio (solo espacios)
  it('deberia devolver 400 si el titulo esta vacio', () => {
    const req = { params: { title: '   ' } };
    const res = createMockRes();

    searchBooks(req, res);

    expect(res.statusCode).to.equal(400);
    expect(res.body.success).to.equal(false);
    expect(res.body.error).to.include('obligatorio');
  });

  // ERROR - Titulo null
  it('deberia devolver 400 si el titulo es null', () => {
    const req = { params: { title: null } };
    const res = createMockRes();

    searchBooks(req, res);

    expect(res.statusCode).to.equal(400);
    expect(res.body.success).to.equal(false);
  });

  // EDGE CASE - Busqueda parcial devuelve varios resultados
  it('deberia devolver varios libros si el termino coincide con varios', () => {
    const req = { params: { title: 'el' } };
    const res = createMockRes();

    searchBooks(req, res);

    expect(res.statusCode).to.equal(200);
    expect(res.body.data.length).to.be.greaterThan(1);
  });

});
